name: Build and push Docker images

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IS_DEFAULT: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile.train
            image_suffix: train
          - dockerfile: Dockerfile.predict
            image_suffix: predict

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build and push
        if: github.event_name != 'pull_request'
        run: |
          IMAGE=${{ env.REGISTRY }}/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')-${{ matrix.image_suffix }}
          BRANCH=${{ github.ref_name }}
          SHA=$(echo ${{ github.sha }} | cut -c1-7)

          docker build -f ${{ matrix.dockerfile }} -t $IMAGE:$BRANCH -t $IMAGE:$SHA .

          if [ "$BRANCH" = "main" ]; then
            docker tag $IMAGE:$BRANCH $IMAGE:latest
            docker push $IMAGE:latest
          fi

          docker push $IMAGE:$BRANCH
          docker push $IMAGE:$SHA
  deploy:
    needs:
      - build-and-push

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: github.event_name == 'push'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ "${{ env.IS_DEFAULT }}" = "true" ]; then
              cd ${{ secrets.COMPOSE_DIRECTORY_PATH }}
              docker compose up -d
            else
              cd ${{ secrets.DEVELOPMENT_COMPOSE_DIRECTORY_PATH }}
              docker compose -p parktrack-dev up -d
            fi

